spiderJson = {"nodes":[
{"weight":2,"rank":6.0, "id":1, "url":"http://www.dr-chuck.com"},
{"weight":4,"rank":19.0, "id":2, "url":"http://www.dr-chuck.com/dr-chuck/resume/index.htm"},
{"weight":1,"rank":5.428571428571418, "id":3, "url":"http://www.dr-chuck.com/office"},
{"weight":1,"rank":1.000000000000002, "id":4, "url":"http://www.dr-chuck.com/sakai-book"},
{"weight":2,"rank":6.0, "id":5, "url":"http://www.dr-chuck.com/dr-chuck/resume/bio.htm"},
{"weight":1,"rank":0.0, "id":10, "url":"http://www.dr-chuck.com/dr-chuck/resume/leadership.htm"},
{"weight":2,"rank":6.0, "id":11, "url":"http://www.dr-chuck.com/dr-chuck/resume/speaking.htm"},
{"weight":1,"rank":5.428571428571418, "id":12, "url":"http://www.dr-chuck.com/dr-chuck/resume/pictures/index.htm"},
{"weight":2,"rank":0.0, "id":13, "url":"http://www.dr-chuck.com/dr-chuck/resume"},
{"weight":1,"rank":5.428571428571418, "id":14, "url":"http://www.dr-chuck.com/dr-chuck/resume/pictures"}],
"links":[
{"source":0,"target":1,"value":3},
{"source":0,"target":2,"value":3},
{"source":0,"target":3,"value":3},
{"source":1,"target":0,"value":3},
{"source":1,"target":4,"value":3},
{"source":1,"target":5,"value":3},
{"source":1,"target":6,"value":3},
{"source":1,"target":7,"value":3},
{"source":1,"target":8,"value":3},
{"source":4,"target":1,"value":3},
{"source":4,"target":6,"value":3},
{"source":4,"target":9,"value":3},
{"source":5,"target":1,"value":3},
{"source":6,"target":1,"value":3},
{"source":6,"target":4,"value":3},
{"source":8,"target":0,"value":3},
{"source":8,"target":8,"value":3}]};
